# Generated by Django 4.1.7 on 2023-02-24 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0002_remove_answer_is_correct_answer_score_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='score',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
