# Generated by Django 4.1.7 on 2023-02-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_remove_useranswer_score_useranswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
